config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  omniauth_callbacks: "omniauth_callbacks"
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tops#index"
  get "/rooms", to: "rooms#index"
  resources :rooms do
    resources :checklists do
      member do
        patch :toggle
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/checklist.rb
class Checklist < ApplicationRecord
  belongs_to :room
  belongs_to :user, optional: true
end

app/models/layout.rb
class Layout < ApplicationRecord
  has_many :rooms, dependent: :destroy
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user, optional: true
  has_many :checklists, dependent: :destroy
  belongs_to :layout, optional: true

  scope :templates, -> { where(is_template: true) }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :rooms
    has_many :checklists

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[line]

  def social_profile(provider)
  social_profiles.select { |sp| sp.provider == provider.to_s }.first
  end

  def set_values(omniauth)
    return if provider.to_s != omniauth["provider"].to_s || uid != omniauth["uid"]
    credentials = omniauth["credentials"]
    info = omniauth["info"]

    access_token = credentials["refresh_token"]
    access_secret = credentials["secret"]
    credentials = credentials.to_json
    name = info["name"]
    # self.set_values_by_raw_info(omniauth['extra']['raw_info'])
  end

  def set_values_by_raw_info(raw_info)
    self.raw_info = raw_info.to_json
    self.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  def index
    @checklists = Checklist.all
  end

  def new
    @room = Room.find(params[:room_id])
    @checklist = Checklist.new
  end

  def show
    @room = Room.find(params[:room_id])
    @checklist = @room.checklists.find(params[:id])
  end

  def create
    @room = Room.find(params[:room_id])
    @checklist = @room.checklists.new(checklist_params.merge(user: current_user))
    if @checklist.save
      flash.now.notice = "チェックリストを追加しました。"
    else
      render :new
    end
  end

  def edit
    @room = Room.find(params[:room_id])
    @checklist = @room.checklists.find(params[:id])
  end

  def update
    @room = Room.find(params[:room_id])
    @checklist = @room.checklists.find(params[:id])
    if @checklist.update(checklist_params)
      flash.now.notice = "チェックリストを更新しました。"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def toggle
    @room = Room.find(params[:room_id])
    @checklist = Checklist.find(params[:id])
    @checklist.update(checked: !@checklist.checked)  # ここで@checklistが正しいChecklistモデルのインスタンスになる

    render turbo_stream: turbo_stream.replace(
      @checklist,
      partial: 'checked',
      locals: { checklist: @checklist }
    )
  end

  def destroy
    @room = Room.find(params[:room_id])
    @checklist = Checklist.find(params[:id])
    @checklist.destroy
    flash.now.notice = "チェックリストを削除しました。"
  end

  private
  def checklist_params
    params.require(:checklist).permit(:name, :checked)
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def line; basic_action end

  private
  def basic_action
    @omniauth = request.env["omniauth.auth"]
    if @omniauth.present?
      @profile = User.find_or_initialize_by(provider: @omniauth["provider"], uid: @omniauth["uid"])
      if @profile.email.blank?
        email = @omniauth["info"]["email"] ? @omniauth["info"]["email"] : "#{@omniauth["uid"]}-#{@omniauth["provider"]}@example.com"
        @profile = current_user || User.create!(provider: @omniauth["provider"], uid: @omniauth["uid"], email: email, name: @omniauth["info"]["name"], password: Devise.friendly_token[0, 20])
      end
      @profile.set_values(@omniauth)
      sign_in(:user, @profile)
    end
    flash[:notice] = "ログインしました"
    redirect_to rooms_path
  end

  def fake_email(uid, provider)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
  # 以上を追加
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms
  def index
    if user_signed_in?
      # 登録ユーザーの場合: 自分が追加した部屋とテンプレートの部屋を表示
      @rooms = current_user.rooms + Room.where(is_template: true)
    else
      # 未登録ユーザーの場合: テンプレートの部屋のみ表示
      @rooms = Room.where(is_template: true)
    end
  end

  # GET /rooms/1
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  def create
    @room = current_user.rooms.new(room_params)

    if @room.save
      flash.now.notice = "部屋を登録しました。"
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /rooms/1
  def update
    if @room.update(room_params)
      flash.now.notice = "部屋を更新しました。"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /rooms/1
  def destroy
    @room.destroy
    flash.now.notice = "部屋を削除しました。"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :age)
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @layouts = Layout.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def turbo_stream_flash
    turbo_stream.update "flash", partial: "flash"
  end
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/application/_flash.html.erb
<% if notice %>
  <div class="bg-teal-100 border border-teal-200 text-sm text-teal-800 rounded-lg p-4 dark:bg-teal-800/10 dark:border-teal-900 dark:text-teal-500" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="bg-red-100 border border-red-200 text-sm text-red-800 rounded-lg p-4 dark:bg-red-800/10 dark:border-red-900 dark:text-red-500" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/application/_modal.html.erb
<dialog id="my_modal_1" class="modal">
  <div class="modal-box">
    <h3 class="font-bold text-lg">大掃除おつかれさまです！よいお年を！</h3>
    <%= image_tag 'yoiotosiwo.png' %>
    <div class="modal-action">
      <form method="dialog">
        <button class="btn" onclick="document.getElementById('my_modal_1').close();">閉じる</button>
      </form>
    </div>
  </div>
</dialog>

app/views/checklists/_checked.html.erb
<%= turbo_frame_tag checklist do %>
  <%= form_with model: checklist, url: [:toggle, checklist.room, checklist] do |f| %>
    <label class="<%= checklist.checked? ? 'checked' : '' %>">
      <%= f.check_box :checked,
                      onchange: "this.form.requestSubmit()",
                      class: "shrink-0 mt-0.5 border-gray-200 rounded text-blue-600 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-gray-800 dark:border-gray-700 dark:checked:bg-blue-500 dark:checked:border-blue-500 dark:focus:ring-offset-gray-800"
                      %>
      <span class="text-sm text-gray-500 ms-3 dark:text-gray-400"><%= checklist.name %></span>
    </label>
  <% end %>
<% end %>

app/views/checklists/_checklist.html.erb
<%= turbo_frame_tag "room_#{room.id}_checklist_#{checklist.id}" do %>
  <li class="w-full inline-flex items-center gap-x-2 py-3 px-4 text-sm font-medium bg-white border text-gray-800 -mt-px first:rounded-t-lg first:mt-0 last:rounded-b-lg dark:bg-gray-800 dark:border-gray-700 dark:text-white">
    <div class="relative flex items-start w-full">
      <%= render 'checklists/checked', checklist: checklist %>
    </div>
      <!-- 編集・削除ボタン -->
    <div class="flex items-center gap-x-2">
    <% if checklist.user_id && checklist.user == current_user %>
      <!-- 編集ボタン -->
        <%= link_to edit_room_checklist_path(room, checklist), data: { turbo_frame: "room_#{room.id}_checklist_#{checklist.id}" }, class: "flex flex-shrink-0 justify-center items-center gap-2 h-[2.875rem] w-[2.875rem] text-sm font-semibold rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700" do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="flex-shrink-0 w-4 h-4 icon icon-tabler icon-tabler-edit" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M7 7h-1a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-1" /><path d="M20.385 6.585a2.1 2.1 0 0 0 -2.97 -2.97l-8.415 8.385v3h3l8.385 -8.415z" /><path d="M16 5l3 3" /></svg>
        <% end %>

        <!-- 削除ボタン -->
        <%= link_to room_checklist_path(room, checklist), data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" }, class: "flex flex-shrink-0 justify-center items-center gap-2 h-[2.875rem] w-[2.875rem] text-sm font-semibold rounded-lg border border-transparent bg-red-600 text-white hover:bg-red-700" do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="flex-shrink-0 w-4 h-4 icon icon-tabler icon-tabler-trash" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M4 7l16 0" /><path d="M10 11l0 6" /><path d="M14 11l0 6" /><path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" /><path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" /></svg>
        <% end %>
      <% end %>
    </div>
  </li>
<% end %>

app/views/checklists/_form.html.erb
<%= turbo_frame_tag "room_#{room.id}_checklist_#{checklist.id}" do %>
  <li class="w-full items-center gap-x-2 py-3 px-4 text-sm font-medium bg-white border text-gray-800 -mt-px first:rounded-t-lg first:mt-0 last:rounded-b-lg dark:bg-gray-800 dark:border-gray-700 dark:text-white">
    <%= form_with model: [room, checklist], data: { turbo_frame: dom_id(room, :checklist) } do |form| %>
      <div class="relative flex items-start w-full">
        <label for="hs-list-group-item-checkbox-1" class="ms-3.5 block w-full text-sm text-gray-600 dark:text-gray-500">
          <%= form.text_field :name, class: "py-3 px-4 block w-full border-gray-200 rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:ring-gray-600", placeholder: "掃除箇所" %>
        </label>
        <div class="flex items-center gap-x-2 pl-6">
        <%= form.submit "追加", class:"flex flex-shrink-0 justify-center items-center gap-2 h-[2.875rem] w-[2.875rem] text-sm font-semibold rounded-lg border border-transparent bg-teal-100 text-teal-800 hover:bg-teal-200 disabled:opacity-50 disabled:pointer-events-none dark:hover:bg-teal-900 dark:text-teal-500 dark:hover:text-teal-400 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" %>
        <%= link_to "×", rooms_path, type:"button", class:"flex flex-shrink-0 justify-center items-center gap-2 h-[2.875rem] w-[2.875rem] text-sm font-semibold rounded-lg border border-transparent bg-gray-100 text-gray-800 hover:bg-gray-200 disabled:opacity-50 disabled:pointer-events-none dark:bg-white/10 dark:hover:bg-white/20 dark:text-white dark:hover:text-white dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600 flex gap-x-2" %>
        </div>
      </div>
    <% end %>
  </li>
<% end %>

app/views/checklists/create.turbo_stream.erb
<%= turbo_stream.prepend "checklists_room_#{@checklist.room_id}", partial: 'checklists/checklist', locals: { room: @room, checklist: @checklist }  %>
<%= turbo_stream.update "room_#{@room.id}_checklist_", "" %>
<%= turbo_stream_flash %>

app/views/checklists/destroy.turbo_stream.erb
<%= turbo_stream.remove "room_#{@room.id}_checklist_#{@checklist.id}" %>
<%= turbo_stream_flash %>

app/views/checklists/edit.html.erb
<h1>チェックリストを編集する</h1>

<%= render 'form', checklist: @checklist, room: @room %>

app/views/checklists/new.html.erb
<h1>チェック項目を登録する</h1>

  <%= render 'form', checklist: @checklist, room: @room %>

<br>

<div>
  <%= link_to "戻る", rooms_path %>
</div>

app/views/checklists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @checklist %>

<div>
  <%= link_to "Edit this checklist", edit_cheklist_path(@checklist) %> |
  <%= link_to "Back to checklists", cheklists_path %>

  <%= button_to "Destroy this checklist", @checklist, method: :delete %>
</div>

app/views/checklists/update.turbo_stream.erb
<%= turbo_stream.replace "room_#{@room.id}_checklist_#{@checklist.id}", partial: 'checklists/checklist', locals: { room: @room, checklist: @checklist }  %>
<%= turbo_stream_flash %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YearendCleaning</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://kit-pro.fontawesome.com/releases/v5.15.1/css/pro.min.css" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "checklist", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="col my-4">
      <div id="flash">
        <%= render "flash" %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= turbo_frame_tag @room do %>
  <div class="hs-accordion active bg-white border -mt-px first:rounded-t-lg last:rounded-b-lg dark:bg-gray-800 dark:border-gray-700" id="hs-bordered-heading-two">
    <%= form_with(model: @room) do |form| %>
      <div class="col-4 pl-2">
        <%= form.text_field :name, class: "py-3 px-4 block w-full border-gray-200 rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:ring-gray-600", placeholder: "This is placeholder" %>
        <%= form.submit "追加する", class:"py-3 px-4 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-teal-100 text-teal-800 hover:bg-teal-200 disabled:opacity-50 disabled:pointer-events-none dark:hover:bg-teal-900 dark:text-teal-500 dark:hover:text-teal-400 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" %>
        <%= link_to "キャンセル", @room, type:"button", class:"py-3 px-4 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-gray-100 text-gray-800 hover:bg-gray-200 disabled:opacity-50 disabled:pointer-events-none dark:bg-white/10 dark:hover:bg-white/20 dark:text-white dark:hover:text-white dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<%= turbo_frame_tag room do %>
  <div class="hs-accordion bg-white border -mt-px first:rounded-t-lg last:rounded-b-lg dark:bg-gray-800 dark:border-gray-700" id="hs-bordered-heading-two">
    <button class="hs-accordion-toggle hs-accordion-active:text-blue-600 inline-flex items-center justify-between w-full font-semibold text-start text-gray-800 py-4 px-5 hover:text-gray-500 disabled:opacity-50 disabled:pointer-events-none dark:hs-accordion-active:text-blue-500 dark:text-gray-200 dark:hover:text-gray-400 dark:focus:outline-none dark:focus:text-gray-400" aria-controls="hs-basic-bordered-collapse-two">
      <div class="flex items-center gap-x-3">
        <svg class="hs-accordion-active:hidden block w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m6 9 6 6 6-6"/></svg>
        <svg class="hs-accordion-active:block hidden w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m18 15-6-6-6 6"/></svg>
        <%= room.name %>
      </div>
    <div class="flex items-center gap-x-2">
      <% if user_signed_in? %>
        <%= link_to new_room_checklist_path(room),  data: { turbo_frame: "room_#{room.id}_checklist_" }, class: "py-3 px-4 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-gray-100 text-gray-800 hover:bg-gray-200 disabled:opacity-50 disabled:pointer-events-none dark:bg-white/10 dark:hover:bg-white/20 dark:text-white dark:hover:text-white dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600"  do %>
          チェックリスト追加
        <% end %>
      <% end %>
      <% if room.user_id && room.user == current_user %>
        <!-- 編集ボタン -->
        <%= link_to edit_room_path(room), class: "flex flex-shrink-0 justify-center items-center gap-2 h-[2.875rem] w-[2.875rem] text-sm font-semibold rounded-lg border border-transparent bg-white text-gray-800 hover:bg-gray-200 disabled:opacity-50 disabled:pointer-events-none dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="flex-shrink-0 w-4 h-4 icon icon-tabler icon-tabler-edit" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M7 7h-1a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-1" /><path d="M20.385 6.585a2.1 2.1 0 0 0 -2.97 -2.97l-8.415 8.385v3h3l8.385 -8.415z" /><path d="M16 5l3 3" /></svg>
        <% end %>

        <!-- 削除ボタン -->
        <%= link_to room, data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" }, class: "flex flex-shrink-0 justify-center items-center gap-2 h-[2.875rem] w-[2.875rem] text-sm font-semibold rounded-lg border border-transparent bg-white text-gray-800 hover:bg-gray-200 disabled:opacity-50 disabled:pointer-events-none dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="flex-shrink-0 w-4 h-4 icon icon-tabler icon-tabler-trash" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M4 7l16 0" /><path d="M10 11l0 6" /><path d="M14 11l0 6" /><path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" /><path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" /></svg>
        <% end %>
      <% end %>
    </div>
    </button>

    <div id="hs-basic-bordered-collapse-two" class="hs-accordion-content hidden w-full overflow-hidden transition-[height] duration-300" aria-labelledby="hs-bordered-heading-two">
      <div class="pb-4 px-5">
        <ul class="max-w-sm flex flex-col">
          <%= turbo_frame_tag "room_#{room.id}_checklist_" %>
          <div id="checklists_room_<%= room.id %>">
            <% room.checklists.each do |checklist| %>
              <%= render 'checklists/checklist', room: room, checklist: checklist %>
            <% end %>
          </div>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/rooms/create.turbo_stream.erb
<%= turbo_stream.prepend "rooms", @room %>
<%= turbo_stream.update Room.new, "" %>
<%# <%= turbo_stream_flash %>

app/views/rooms/destroy.turbo_stream.erb
<%= turbo_stream.remove @room %>
<%= turbo_stream_flash %>

app/views/rooms/edit.html.erb
<h1>部屋を編集する</h1>

<%= render "form", cat: @room %>

app/views/rooms/index.html.erb
<div class="bg-body-dark py-6 sm:py-8 lg:py-12">
  <div class="mx-auto max-w-screen-lg px-4 md:px-8">
    <div class="pb-4 items-end">
      <% if user_signed_in? %>
        <%= link_to new_room_path, data: { turbo_frame: dom_id(Room.new) }, class: "py-3 px-4 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-gray-100 text-gray-800 hover:bg-gray-200 disabled:opacity-50 disabled:pointer-events-none dark:bg-white/10 dark:hover:bg-white/20 dark:text-white dark:hover:text-white dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" do %>
          部屋の追加
        <% end %>
      <% end %>
    </div>
<!-- 一覧 -->
  <%= turbo_frame_tag Room.new %>

  <div class="hs-accordion-group">
    <div id="rooms">
      <%= render @rooms %>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<h1>部屋を登録する</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "戻る", rooms_path %>
</div>

app/views/rooms/show.html.erb
<%= render @room %>

app/views/rooms/update.turbo_stream.erb
<%= turbo_stream.replace @room %>
<%= turbo_stream_flash %>

app/views/shared/_header.html.erb
<div class="navbar bg-base-100">
  <div class="navbar-start"></div>
  <div class="navbar-center ">
    <a href="<%= rooms_path %>" class="btn btn-ghost text-xl">大掃除チェックリスト</a>
  </div>
  <div class="navbar-end">
  <!-- Open the modal using ID.showModal() method -->
  <button class="btn" onclick="my_modal_2.showModal()">大掃除終わった？</button>
  <dialog id="my_modal_2" class="modal">
    <div class="modal-box">
      <h3 class="font-bold text-lg">大掃除おつかれさまです！よいお年を！</h3>
      <%= image_tag 'yoiotosiwo.png' %>
    </div>
    <form method="dialog" class="modal-backdrop">
      <button>close</button>
    </form>
  </dialog>
  <% if user_signed_in? %>
    <!-- ユーザーがログインしている場合 -->
    <span class="inline-block h-[2.375rem] w-[2.375rem] bg-gray-100 rounded-full overflow-hidden">
      <svg class="h-full w-full text-gray-300" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="0.62854" y="0.359985" width="15" height="15" rx="7.5" fill="white"/>
        <path d="M8.12421 7.20374C9.21151 7.20374 10.093 6.32229 10.093 5.23499C10.093 4.14767 9.21151 3.26624 8.12421 3.26624C7.0369 3.26624 6.15546 4.14767 6.15546 5.23499C6.15546 6.32229 7.0369 7.20374 8.12421 7.20374Z" fill="currentColor"/>
        <path d="M11.818 10.5975C10.2992 12.6412 7.42106 13.0631 5.37731 11.5537C5.01171 11.2818 4.69296 10.9631 4.42107 10.5975C4.28982 10.4006 4.27107 10.1475 4.37419 9.94123L4.51482 9.65059C4.84296 8.95684 5.53671 8.51624 6.30546 8.51624H9.95231C10.7023 8.51624 11.3867 8.94749 11.7242 9.62249L11.8742 9.93184C11.968 10.1475 11.9586 10.4006 11.818 10.5975Z" fill="currentColor"/>
      </svg>
    </span>
  <% else %>
    <!-- ユーザーがログインしていない場合 -->
  <% end %>
  </div>
</div>

app/views/tops/index.html.erb
<div class=" bg-body-dark py-6 sm:py-8 lg:py-12">
  <div class="mx-auto max-w-screen-lg px-4 md:px-8">
    <div class="card flex-auto bg-base-100 shadow-xl text-center">
      <div class="card-body pt-8 pb-8">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">使い方</h1>
        <p class="mb-8 leading-relaxed">
        <br>LINEログインしてから使ってください〜〜〜<br>
        </p>
        <%= link_to user_line_omniauth_authorize_path, class: 'block mx-auto', method: :post do %>
          <%= image_tag 'btn_login_base.png' %>
        <% end %>
        <%= link_to "チェックリストへ" ,rooms_path,  method: :get %>
      </div>
    </div>
  </div>
</div>